### ISSUE TITLE
Yarn: webpack dependency not provided

### ISSUE THREAD

**Issue by Robula** [vuejs/eslint-config-standard#7]
```
❯ yarn
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @vue/eslint-config-standard@npm:6.0.0 [4ab08] doesn't provide webpack (p0da10), requested by eslint-import-resolver-webpack
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 359ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 347ms
➤ YN0000: Done with warnings in 0s 926ms
```
```
❯ yarn explain peer-requirements p0da10      
➤ YN0000: @vue/eslint-config-standard@npm:6.0.0 [4ab08] doesn't provide webpack, breaking the following requirements:

➤ YN0000: eslint-import-resolver-webpack@npm:0.13.0 [93f0f] → >=1.11.0 ✘
```

Since `webpack` is provided by `@vue/cli-service` should the following be added to this package's config?:
``` 
"peerDependenciesMeta": {
    "webpack": {
      "optional": true
    }
  }
```

### Workaround
Users can work around this by adding this to their `yarnrc.yml`:
```yaml
packageExtensions:
  "@vue/eslint-config-standard@^6.0.0":
    peerDependenciesMeta:
      webpack:
        optional: true
````
